# Generated by Django 4.1.1 on 2022-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vehicle_no',
            field=models.CharField(max_length=50),
        ),
    ]
